export const ActionTypes = {
  SERACH_NAME_DRINK: "SERACH_NAME_DRINK",
  SAVE_DRINK: "SAVE_DRINK",
  DISPLAY_ALL_DRINK: "DISPLAY_ALL_DRINK",
  SHOW_DRINK : "SHOW_DRINK",
  SORT_BY_NAME_DATA:"SORT_BY_NAME_DATA",
  FILTER_DRINK_INPUT:"FILTER_DRINK_INPUT"
};
